### ISSUE TITLE
getservers adds hacknet-servers for hacking

### ISSUE THREAD

**Issue by schlaubi69** [kamukrass/Bitburner#8]
I'm on Bitnode 9, distributed-hack-script uses the hacknetservers for hacking. The hacknet-Servers shouldn't be used for hacking but for hash-production.
Please add in distributed-hack and/or get-servers something to ommit servers with name-scheme "hacknet-node-0", "hacknet-node-1" and so on.

**Comment by DromaTheRyn** [comment]
Change the function **scanAndNuke(ns)** to:

`async function scanAndNuke(ns) {
	let servers = new Set(["home"]);
	scanAll(ns, "home", servers);
	var accessibleServers = new Set();
	let i = 0;
	for (let server of servers) {
		if (server == "hacknet-node-" + i) {
			i++;
			//do nothing
		}
		else {
			if (await ns.hasRootAccess(server)) {
				accessibleServers.add(server)
			} else {
				var portOpened = 0;
				if (await ns.fileExists("BruteSSH.exe")) {
					await ns.brutessh(server);
					portOpened++;
				}
				if (await ns.fileExists("FTPCrack.exe")) {
					await ns.ftpcrack(server);
					portOpened++;
				}
				if (await ns.fileExists("HTTPWorm.exe")) {
					await ns.httpworm(server);
					portOpened++;
				}
				if (await ns.fileExists("relaySMTP.exe")) {
					await ns.relaysmtp(server);
					portOpened++;
				}
				if (await ns.fileExists("SQLInject.exe")) {
					await ns.sqlinject(server);
					portOpened++;
				}
				if (await ns.getServerNumPortsRequired(server) <= portOpened) {
					await ns.nuke(server);
					accessibleServers.add(server);
				}
			}
		}
	}
	return accessibleServers;
}`

It may not be elegant, but it works.

**Comment by schlaubi69** [comment]
Thanks for the quick response, I've added this line in function getFreeRam, seems to work
for (let server of servers) {

> if (server.startsWith("hacknet-node")) { continue; }

...

**Comment by kamukrass** [comment]
Thanks for the report and improvement proposal. Solved in https://github.com/kamukrass/Bitburner/pull/10
